version: '3.8'

services:
    nginx_manager:
        image: jc21/nginx-proxy-manager:latest
        container_name: 'nginx_manager'
        restart: unless-stopped
        networks: [default]
        ports:
            - '80:80'
            - '443:443'
            - '81:81'
        environment:
            DB_MYSQL_HOST: "mariadb"
            DB_MYSQL_PORT: 3306
            DB_MYSQL_USER: "nginx_manager"
            DB_MYSQL_PASSWORD: "RRHSjgwPTMA1RRHSjgwPTMA1"
            DB_MYSQL_NAME: "nginx_manager"
        volumes:
            - ./www/data:/data
            - ./www/letsencrypt:/etc/letsencrypt
        depends_on:
            - mariadb

    mariadb:
        image: 'jc21/mariadb-aria:latest'
        restart: unless-stopped
        networks: [default]
        environment:
            MYSQL_ROOT_PASSWORD: 'XVqwBEZIt6jpXVqwBEZIt6jp'
            MYSQL_DATABASE: 'nginx_manager'
            MYSQL_USER: 'nginx_manager'
            MYSQL_PASSWORD: 'RRHSjgwPTMA1RRHSjgwPTMA1'
        volumes:
            - ./www/mysql:/var/lib/mysql

networks:
    default:
        external: true
        name: proxy